### PR TITLE
Make S3 support optional

### PR DESCRIPTION
**Pull request by akalsey**

### CODE REVIEW

**Comment by tabacco** [comment]
Looks good, but conflicts with your error handling change - could you resolve the conflicts with master and push up the change?

**Comment by tabacco** [comment]
Oh hmm, probably shouldn't have merged that. I think the intended behavior there was to load from disk if s3 isn't configured, right?

**Comment by tabacco** [comment]
Oh nevermind, I may have misread.

**Comment by akalsey** [comment]
Intent is to only trigger S3 commands if S3 is configured. Otherwise, everything just stays on disk. In my project, I'm using Docker Volumes mounted at /root/saves and /root/zcode to provide permanent storage, so s3 is redundant.

If s3 isn't configured, the functions that call S3 are never loaded, and even the s3 npm module isn't required.

**Comment by tabacco** [comment]
Yeah sorry, I was looking at the last commit out of context and commented too soon.

**Pull request merged**
